### ISSUE TITLE
Update Admin Pages: Attributes

### ISSUE THREAD

**Issue by saliozzia** [loadedcommerce/Loaded6CE#114]

**Comment by saliozzia** [comment]
@jimmcget please add any comments on these issues 
pass, fail, and the reason for fail.

**Comment by jimmcget** [comment]
@saliozzia will do

**Comment by jimmcget** [comment]
Pass
 in CE version had not issues with adding any attributes at all
http://www.magnumwebdesign.com/653ce/product_info.php?cPath=20&products_id=60
