### ISSUE TITLE
Upgrader issue with file_get_contacts()

### ISSUE THREAD

**Issue by saliozzia** [loadedcommerce/Loaded6CE#12]
_From @wa4u on November 16, 2015 17:56_

Some servers do not support file_get_contacts(), update file_get_contacts() with curl.

_Copied from original issue: loadedcommerce/loaded6#11_

**Comment by devidash** [comment]
There is no such default function available called file_get_contacts. Either it is file_get_contents or it is a custom function. Please give me on which page it is throwing error, i can solve it.

**Comment by devidash** [comment]
I have tried but not got this issue. I think we are fine with this.
