### ISSUE TITLE
Category / Product edit page design issues

### ISSUE THREAD

**Issue by wa4u** [loadedcommerce/Loaded6CE#17]
admin/category.php - which is responsible for category and product add / edit does not have proper layout.

**Comment by saliozzia** [comment]
Specifically fix the language tab selection on page load for product edit

**Comment by devidash** [comment]
I have fixed this in my dev server URL is below. 
http://devi.trhsecure.com/65/
Login: support@loadedcommerce.com
Pass: Google@99

Same login info as Kiran's test site.
