### ISSUE TITLE
b2b restrictions on categories ingored 

### ISSUE THREAD

**Issue by saliozzia** [loadedcommerce/Loaded6CE#18]
check for guest and other group privileges on displaying categories entries in category infobox

![image](https://cloud.githubusercontent.com/assets/2836269/12115591/7649388c-b381-11e5-9133-740349445e82.png)

**Comment by saliozzia** [comment]
this particular item has no rights for any groups, 

http://store.loadedcommerce.com/admin/categories.php?cPath=&cID=47&action=edit_category&osCAdminID=bddbebce08048bad2d90ab3376fb5426

![image](https://cloud.githubusercontent.com/assets/2836269/12115662/0bb38d28-b382-11e5-91a7-db086cdd87f8.png)

which means it should not appear for anyone.

**Comment by devidash** [comment]
This is fixed. Please check and confirm.

**Comment by devidash** [comment]
Merged & deleted the branch. Closing task.
