### ISSUE TITLE
CDS and Product Category infobox style issues

### ISSUE THREAD

**Issue by saliozzia** [loadedcommerce/Loaded6CE#23]
CDS box and PRoduct Category box shoudl have same visual style.

Use Category Title left padding for all left padding.
Use Category link line spacing for CDS line Spacing
Reduce and match second level links in CDS box

![image](https://cloud.githubusercontent.com/assets/2836269/12125899/160cb5a8-b3bc-11e5-812a-010e875e7adb.png)

**Comment by devidash** [comment]
Fixed. Please check and confirm.
