### ISSUE TITLE
CDS Page Manager

### ISSUE THREAD

**Issue by wa4u** [loadedcommerce/Loaded6CE#31]
CDS Page Manager add / edit pages layout is not good.

**Comment by wa4u** [comment]
![screenshot_13](https://cloud.githubusercontent.com/assets/3207057/12433038/d2a652aa-bf24-11e5-83ea-0f35daf8779c.png)

![screenshot_14](https://cloud.githubusercontent.com/assets/3207057/12433040/d4125d78-bf24-11e5-819d-b9b6e65e934f.png)

**Comment by wa4u** [comment]
Committed to #36

**Comment by devidash** [comment]
Released.
