### ISSUE TITLE
Right Column Infoboxes do not work.

### ISSUE THREAD

**Issue by jimmcget** [loadedcommerce/Loaded6CE#43]

**Comment by jimmcget** [comment]
Turning on the right column infoboxes, do not show up and does not show changes in mainpage size.

Moved Pages.php infobox to right column:

![Screenshot](http://grabilla.com/0611a-d0cd0b31-4d93-44f8-85d3-bbc1bce08754.png)

Mainpage view:

![Screenshot](http://grabilla.com/0611a-b5fc07e7-4182-44e6-bc9b-bc3ad21c09de.png)

Right Column turned on in template manager:

![Screenshot](http://grabilla.com/0611a-de3fb489-4548-40cd-ac79-0929760f63d9.png)

**Comment by devidash** [comment]
Fixed.

**Comment by devidash** [comment]
released.
