### ISSUE TITLE
Banner Manager - Creating new banner - No groups to select -

### ISSUE THREAD

**Issue by jimmcget** [loadedcommerce/Loaded6CE#44]
We need some preset selections showing for new banners, such as BoxAd, Most customers do not know how to create these. boxad is un-editable  you cannot edit it from banner manager, using boxad as a group,.

I created googlead and boxad group, either of these infoboxes work.

**Comment by saliozzia** [comment]
banner groups are made when you make banners, so the first banner you must set the group as instructed. not a bug
