### ISSUE TITLE
Links - Infobox heading not updating when adding a heading title

### ISSUE THREAD

**Issue by jimmcget** [loadedcommerce/Loaded6CE#45]
Infobox heading added:
![Screenshot](http://grabilla.com/0611a-b35a7b51-f625-41fd-a8c7-118477b1abaa.png)

After Update:
![Screenshot](http://grabilla.com/0611a-80fbfa7d-e18b-468c-9036-33b91f3174e8.png)

Mainpage View:
![Screenshot](http://grabilla.com/0611a-c9fa5207-e922-4736-aba0-4a8c32250dbd.png)

**Comment by devidash** [comment]
Fixed

**Comment by devidash** [comment]
released.
