### ISSUE TITLE
Example Infobox Heading - Not saving - No Infobx Header on mainpage.

### ISSUE THREAD

**Issue by jimmcget** [loadedcommerce/Loaded6CE#48]
Template manager - Infoboxes

![Screenshot](http://grabilla.com/0611a-fd91bd3a-1255-49a6-a43b-ea41d18ce447.png)

Mainpage view
![Screenshot](http://grabilla.com/0611a-b5bf17f7-e788-4d64-8b23-5c8289d010f6.png)

**Comment by saliozzia** [comment]
Jim, the example box probably does not have a header, its just html code that lives in the box.php file. please let us know if this page works as designed - controlling  box positions in general.

**Comment by jimmcget** [comment]
Sal, it does work as it is suppose to.

**Comment by devidash** [comment]
This is fixed in issue #45
