### ISSUE TITLE
Admin - Edit Profile - throws error

### ISSUE THREAD

**Issue by jimmcget** [loadedcommerce/Loaded6CE#49]
Clicking on edit Profile in the 6.5.3 Admin 

Throws error page not found.

**Comment by jimmcget** [comment]
Error seems to be a mis-spelling error

https://www.magnumwebdesign.com/653_ce/admin/ILENAME_ADMIN_ACCOUNT

**Comment by jimmcget** [comment]
Found the error,

In admin/includes/header.php 

<?php echo tep_href_link(ILENAME_ADMIN_ACCOUNT,'','SSL');?>">Edit Profile</a>

**Comment by jimmcget** [comment]
<li><a href="<?php echo tep_href_link(ILENAME_ADMIN_ACCOUNT,'','SSL');?>">Edit Profile</a></li>

**Comment by jimmcget** [comment]
Fix is
<?php echo tep_href_link(FILENAME_ADMIN_ACCOUNT,'','SSL');?>">Edit Profile

**Comment by devidash** [comment]
Merged to rc2
