### ISSUE TITLE
6.5.3 CE RC1 -Creating new product  - Page out of styling - Way to large

### ISSUE THREAD

**Issue by jimmcget** [loadedcommerce/Loaded6CE#56]
See screenshot:
![Screenshot](http://grabilla.com/06201-4098453c-d0af-4cf0-83ee-9221a9b666cd.png)

**Comment by jimmcget** [comment]
Also no product description area, or editor showing, also no product name can be entered

**Comment by jimmcget** [comment]
Product page looks l;ike this:
![Screenshot](http://grabilla.com/06201-30464f1e-a695-4c1a-940b-131a0e39bdd3.png)

**Comment by saliozzia** [comment]
Issue for now is language content is not selected.

**Comment by wa4u** [comment]
Below explanation holds good for new product / edit product
- If we have more then 1 language tabs show. No description editor on products.
- Clicking on language tab shows product description editor.
- Categories use old tab code, only product pages have new bootstrap code.

## No editor / No tab selected

![No tab selected](https://cloud.githubusercontent.com/assets/3207057/12763261/6ca4e566-ca19-11e5-890e-d0566e72e649.png)

## Tab Selected, we can see editor

![screenshot_19](https://cloud.githubusercontent.com/assets/3207057/12763262/6dc2ab4a-ca19-11e5-8c2b-f8aaab3889c1.png)

## Old Tabs for categories.

![screenshot_20](https://cloud.githubusercontent.com/assets/3207057/12763308/ac753d8a-ca19-11e5-81fd-1a07c44cc404.png)

**Comment by devidash** [comment]
Issue fixed.

**Comment by devidash** [comment]
released.
