### ISSUE TITLE
6.5.3 CE RC1 - Product attributes do not show on catalog side, when assigned to a product.

### ISSUE THREAD

**Issue by jimmcget** [loadedcommerce/Loaded6CE#60]

**Comment by jimmcget** [comment]
You can see here product attributes have been added to the product.
![Screenshot](http://grabilla.com/06202-e3d603a9-6cb6-4f3a-b1eb-6326982bc011.png)

Catalog side showing no attributes:
![Screenshot](http://grabilla.com/06202-f8f49319-7999-46bc-8d65-c876ccc5b554.png)

**Comment by devidash** [comment]
Fixed

**Comment by devidash** [comment]
Released.
