### ISSUE TITLE
Authorize.net new technical changes. Need to apply to all Verisons

### ISSUE THREAD

**Issue by jimmcget** [loadedcommerce/Loaded6CE#64]
Listed here is concerns from our customer requesting information on how this will effect the customer using Authorize net modiule.

Authorize.Net

Authorize.Net Technical Updates

Your Payment Gateway ID: 1147923
Dear Authorize.Net Merchant:

Over the next few months, we are making several updates to our systems 
that you need to be aware of. They are all technical in nature and may 
require the assistance of your web developer or shopping cart/payment 
solution provider.

Please read this email carefully, and if you need to find a web 
developer to help you, please check out our Certified Developer 
Directory at www.authorize.net/cdd 
http://app.payment.authorize.net/e/er?utm_campaign=February%202016%20Technical%20Updates%20for%20Merchants.html&utm_medium=email&utm_source=Eloqua&s=986383348&lid=249&elqTrackId=2af775d6c2874c4bbf917b1f524ad946&elq=13550506b479457aa730c5035002eddf&elqaid=483&elqat=1.

Akamai SureRoute Reminder

As we get further into 2016, we want to remind you of our previously 
announced 
http://app.payment.authorize.net/e/er?utm_campaign=February%202016%20Technical%20Updates%20for%20Merchants.html&utm_medium=email&utm_source=Eloqua&s=986383348&lid=258&elqTrackId=e551f4f2da9e4ba987b0ffc182d8d057&elq=13550506b479457aa730c5035002eddf&elqaid=483&elqat=1 
Akamai SureRoute implementation plan and timelines. Using Akamai's 
technology will help safeguard against interruptions caused by issues 
beyond our direct control, such as Internet congestion, fiber cable cuts 
and other similar issues.

If you have not already, please review the announcement and the Akamai 
FAQs 
http://app.payment.authorize.net/e/er?utm_campaign=February%202016%20Technical%20Updates%20for%20Merchants.html&utm_medium=email&utm_source=Eloqua&s=986383348&lid=250&elqTrackId=e1f2418cb5f74a2f9345c0c3fa78b5d1&elq=13550506b479457aa730c5035002eddf&elqaid=483&elqat=1 
to determine what action you should take for your particular solution. 
_If your solution uses a firewall, please pay particular attention to 
this section of the FAQs 
http://app.payment.authorize.net/e/er?utm_campaign=February%202016%20Technical%20Updates%20for%20Merchants.html&utm_medium=email&utm_source=Eloqua&s=986383348&lid=285&elqTrackId=7ed437136c7349cf8ad37811b19953b4&elq=13550506b479457aa730c5035002eddf&elqaid=483&elqat=1
to make sure you avoid any disruptions to your transaction processing._

Transaction and Batch ID Reminder

In the coming months, due to system updates, it will be possible to 
receive Authorize.Net IDs (Transaction ID, Batch ID, etc.) that are not 
in sequential order.

For example, currently, if you receive a Transaction ID of "1000," you 
could expect that the next Transaction ID would not be less than 1000. 
However, after the updates, it will be possible to receive a Transaction 
ID less than the one previously received.

If your system has any functionality that expects 
Authorize.Net-generated IDs to be sequential, please update it 
immediately so that you will not see any disruptions.

*Additionally, please make sure that your solution does not restrict any 
Authorize.Net ID field to 10 characters. *If you are required to define 
a character limit when storing any of our IDs, the limit should be no 
less than 20 characters.

RC4 Cipher Disablement

In an effort to ensure that all of your server-to-server communications 
with the Authorize.Net platform (both transactional and otherwise) 
maintain the highest levels of security, we will be disabling the RC4 
cipher suite during the first half of 2016. A follow-up notification 
will be sent out once specific dates for the disablement are ready for 
the sandbox and production environments.

For now, if you have a solution that relies on RC4 to communicate with 
our servers, please update it to a current, high-security cipher as soon 
as possible. Please review our API best practices blog post 
http://app.payment.authorize.net/e/er?utm_campaign=February%202016%20Technical%20Updates%20for%20Merchants.html&utm_medium=email&utm_source=Eloqua&s=986383348&lid=286&elqTrackId=89a3757320cf4973a79bb47e8ee74560&elq=13550506b479457aa730c5035002eddf&elqaid=483&elqat=1
for more information.

TLS Remediation for PCI DSS Compliance

As you may already be aware, new PCI DSS requirements state that all 
payment systems must disable TLS 1.0 by 2018. Though we are still 
finalizing our plans for remediating TLS 1.0 in both sandbox and 
production, we will be disabling TLS 1.0 in sandbox and production in 
early 2017. This is to ensure that we are compliant ahead of the PCI date.

In addition, we are discussing the possibility of disabling TLS 1.1 at 
the same time, because while it is not expressly forbidden, there are 
enough concerns surrounding it. TLS 1.2 is currently the strongest 
available protocol, and we strongly urge all merchants and developer 
partners to use it for their API integrations.

For more information, including updates to the dates we anticipate 
disabling TLS in each environment, please refer to our previous blog 
post 
http://app.payment.authorize.net/e/er?utm_campaign=February%202016%20Technical%20Updates%20for%20Merchants.html&utm_medium=email&utm_source=Eloqua&s=986383348&lid=257&elqTrackId=875234fc23004efeafae73dfcfc8b8e4&elq=13550506b479457aa730c5035002eddf&elqaid=483&elqat=1. 

Sincerely,
Authorize.Net

You have opted to receive Administrative Announcements for your payment 
gateway account. To unsubscribe, log into the Merchant Interface and 
click Account from the main toolbar. Then click User Profile from the 
menu on the left. Select Edit Profile Information and uncheck the email 
types you do not want to receive. Click Submit to save any changes.

For information on how we handle customer information, please see our 
Spam Policy 
http://www.authorize.net/company/spampolicy/?utm_campaign=February%202016%20Technical%20Updates%20for%20Merchants.html&utm_medium=email&utm_source=Eloqua&elq=13550506b479457aa730c5035002eddf&elqCampaignId=325&elqaid=483&elqat=1&elqTrackId=c6c6046238e841f8b2b5ca11ce3cff34 
and Privacy Policy 
http://www.authorize.net/company/privacy/?utm_campaign=February%202016%20Technical%20Updates%20for%20Merchants.html&utm_medium=email&utm_source=Eloqua&elq=13550506b479457aa730c5035002eddf&elqCampaignId=325&elqaid=483&elqat=1&elqTrackId=069b662868f449949e5db02fdc5d2fe0. 
Please do not reply to this email.

© Copyright 2016. Authorize.Net P.O. Box 8999, San Francisco, CA 
94128-8999. All other marks are the property of their respective owners. 
All rights reserved.

**Comment by devidash** [comment]
There is nothing to do with the code. Most of them are server related settings.
