### ISSUE TITLE
6.5.3 RC2 - PayPal payment Module Issue.

### ISSUE THREAD

**Issue by jimmcget** [loadedcommerce/Loaded6CE#68]
When updating PayPal credentials, and information, to use the module.

![Screenshot](http://grabilla.com/0630b-e40302a7-4ec5-416e-b614-a94274ac364f.png)

And after clicking update this happens, all data update information is wiped out.
![Screenshot](http://grabilla.com/0630b-7b85fdc9-96b1-44dc-99d6-7b608131b96b.pngg)

**Comment by devidash** [comment]
Fixed and updated in RC2 Please check and confirm.
