### ISSUE TITLE
6.5.3 CE RC2 Coupon does not deduct from attributes.

### ISSUE THREAD

**Issue by jimmcget** [loadedcommerce/Loaded6CE#69]
![Screenshot](http://grabilla.com/0630b-c22ad478-4355-4fd9-856b-d4f11ba10871.png)

**Comment by jimmcget** [comment]
A better explaination
![Screenshot](http://grabilla.com/0630e-45a428af-6fdb-4bc4-9ba1-86c24e55b0eb.png)

**Comment by devidash** [comment]
I did one test and it work perfect for me. In my case product price is $39.99 and attribute price is $2. I have applied a 10% discount coupon and it deduct $4.20. Screenshot attached.
![2016-03-15_170930](https://cloud.githubusercontent.com/assets/2279128/13776554/c11b950e-ead0-11e5-8249-ab0eab3d0adf.png)

**Comment by jimmcget** [comment]
The issue is caused by adding a product or category for the coupon, it works awesome for full site products, but one you add a product or category, it will not deduct for attributes.
