### ISSUE TITLE
Admin Header upper right

### ISSUE THREAD

**Issue by saliozzia** [loadedcommerce/Loaded6CE#7]
_From @saliozzia on November 26, 2015 19:30_

Add iframe with message page for ads

Leave user drop down in place (as per the target theme)

Add create and search buttons based on mock up but also try to adapt to target theme styles. 

![uploads/53586703-47ff-464a-8d8a-a7639b00de88/admin header right.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F53586703-47ff-464a-8d8a-a7639b00de88%2Fadmin+header+right.png)

_Copied from original issue: loadedcommerce/loaded6#15_

**Comment by wa4u** [comment]
Updated code on dev.
