### ISSUE TITLE
6.5.3 RC2 - Mainpage modules, that do not go with CE version

### ISSUE THREAD

**Issue by jimmcget** [loadedcommerce/Loaded6CE#71]
There are some mainpage modules in the CE version that do not belong there. unless we have a teaser to entice people to purchase the upgrade to Pro or B2B

**Comment by jimmcget** [comment]
FDMS should not be in CE version needs to be removed from mainpage modules folder.

**Comment by devidash** [comment]
This is fixed and updated in the RC2 repo. Please check and confirm.
