### ISSUE TITLE
6.5.3 RC2 Add Voucher credit to customer account does not save.

### ISSUE THREAD

**Issue by jimmcget** [loadedcommerce/Loaded6CE#74]
Added voucher credit to account 400.00
![Screenshot](http://grabilla.com/0630f-8c8d5ae4-f3ce-44b8-929d-ce44f431c766.png)

After clicking update, and returning to check the update voucher, voucher field is blank.
![Screenshot](http://grabilla.com/0630f-c4f195d7-4b0f-43cb-89b2-681c8d1aa913.pngg)

**Comment by jimmcget** [comment]
After further testing on the gift voucher module, I find that after you send an email voucher, you can save the Credit Voucher, from the customer profile edit. I do think if the customer had an issue and a credit is given for any issues, the admin should be able to credit account without having to send a voucher email to customer. But it does work after sending so it is not a priority issue. Please adjust as you need to.

**Comment by devidash** [comment]
Fixed.
