### ISSUE TITLE
branding manager breaks

### ISSUE THREAD

**Issue by saliozzia** [loadedcommerce/Loaded6CE#83]
Trying to update the logo on our store i get this error:

REPLACE INTO branding_description set store_brand_image = 'loadedcommerce50px.png', store_brand_favicon = '', store_brand_slogan = 'Commercial Open Source Ecommerce', store_brand_telephone = '(800) 609-2141', store_brand_fax = '(216) 220-8768', store_brand_homepage = 'http://www.loadedcommerce.com', store_brand_name = 'Loaded Commerce', store_brand_support_email = 'sales@loadedcommerce.com', store_brand_support_phone = '(800) 609-2141', store_brand_address = '', custom_css = '', facebook_link = 'https://facebook.com/loadedcommerce', twitter_link = 'https://twitter.com/loadedcommerce', pinterest_link = '', google_link = '', youtube_link = 'https://www.youtube.com/user/loadedcommerce', linkedin_link = '', language_id = '1'

[TEP STOP]

**Comment by saliozzia** [comment]
i want this image as our logo on the catalog header:
![loadedcommerce50px](https://cloud.githubusercontent.com/assets/2836269/14768106/2a6348e6-0a06-11e6-90a7-a67154137adc.png)

it is sized correctly and has padding. i want this specific file used.

**Comment by saliozzia** [comment]
Branding manager in CE does not have this issue, may only be in B2B (possibly in Pro)

**Comment by wa4u** [comment]
Store db was needed sql update. store_brand_favicon was missing.
Uploaded image provided.
