### ISSUE TITLE
Missing header mesages

### ISSUE THREAD

**Issue by saliozzia** [loadedcommerce/Loaded6CE#9]
_From @wa4u on January 4, 2016 19:17_

Missing header messages of currency update, etc

_Copied from original issue: loadedcommerce/loaded6#18_

**Comment by wa4u** [comment]
Code committed with #18
https://github.com/loadedcommerce/Loaded6CE/commit/bc013e8a87da282c6701dd26ac85d3529423b77a

**Comment by devidash** [comment]
Merged, branch deleted and closed.
