### ISSUE TITLE
sevenofsix header issues

### ISSUE THREAD

**Issue by saliozzia** [loadedcommerce/Loaded6CE#93]
Loaded 7 header:
![image](https://cloud.githubusercontent.com/assets/2836269/15072661/2a9e741a-1362-11e6-97b3-1e4e1965a1f4.png)

Loaded 6 header: 
![image](https://cloud.githubusercontent.com/assets/2836269/15072702/918f70a2-1362-11e6-901a-74e11fc8a2bb.png)
1. Add language and currency Menu - should behave exactly like Loaded 7 UX
2. Accounts is OK
3. Cart is OK
4. text is touching the top header add padding above phone and email (or add padding below top header) 
5. Use H1 style for store name when no logo is used
6. add padding to slogan  
   ![image](https://cloud.githubusercontent.com/assets/2836269/15072821/a16ebcca-1363-11e6-862f-d4486d7cd363.png)  
   when a logo is present the text touches the logo, this image has some white space in the image so its hard to see.
7. remove "TOP" from breadcrumb, "Catalog" renames to "HOME"

Language and Currency menu:
![image](https://cloud.githubusercontent.com/assets/2836269/15072737/df13a3fc-1362-11e6-87b5-006407ff433d.png)

**Comment by wa4u** [comment]
All these updated on store. Once you review, Iw ill commit those to branch.

**Comment by saliozzia** [comment]
the margin on the bottom of the main nav should be the same as the top margin.

![image](https://cloud.githubusercontent.com/assets/2836269/15658857/c865430a-268f-11e6-910b-634664d7bfef.png)

**Comment by saliozzia** [comment]
@wa4u please commit to branch now

**Comment by wa4u** [comment]
Need to include this sql for the mod.

```
INSERT INTO configuration (`configuration_id`, `configuration_title`, `configuration_key`, `configuration_value`, `configuration_description`, `configuration_group_id`, `sort_order`, `last_modified`, `date_added`, `use_function`, `set_function`) VALUES ('', 'Template Header Menu', 'TEMPLATE_CDS_TOPMENU_ID', '0', 'Header CDS Template menu.', '481', '0', now(), now(), NULL, NULL);
```
