### ISSUE TITLE
catalog search results php error

### ISSUE THREAD

**Issue by saliozzia** [loadedcommerce/Loaded6CE#94]
when searching for a product from the header, or from the form on the page we get an error

http://lab.loadedcommerce.com/product/loaded6/advanced_search_result.php?keywords=ifone&osCsid=7d734b019c89f2ba725bc22175b7616b

Fatal error: Call to undefined function hide_add_to_cart() in /home/loadlab/public_html/product/loaded6/templates/sevenofsix/includes/modules/product_listing.php on line 90

**Comment by devidash** [comment]
Issue fixed.
