### ISSUE TITLE
Sevenofsix CSS class names - use IDs

### ISSUE THREAD

**Issue by saliozzia** [loadedcommerce/Loaded6CE#99]
In order to use the custom CSS overrides the class names or div names need to make sense. 

for exmaple the header main nav bar has no meaningful identification in the HTML to address in the CSS.
![image](https://cloud.githubusercontent.com/assets/2836269/15627694/013c7cfc-24ba-11e6-8145-893db66c680d.png)

I beleive we need to use IDs in our html for our templates
http://www.htmldog.com/guides/css/intermediate/classid/

**Comment by saliozzia** [comment]
see what happens why i try to set the background color on the main nav in the inspector:
![image](https://cloud.githubusercontent.com/assets/2836269/15627711/61abd736-24ba-11e6-967a-b4c17d552f26.png)

**Comment by devidash** [comment]
We have already class defined for the menu bar which name is ".navbar-inverse". This is available in the bootstrap.css line number 4036. Please check and let me know.
